- name: Remove bahmni-endtb-batch before installing
  yum:  name=bahmni-endtb-batch state=absent

- name: Install bahmni-endtb-batch
  yum:  name=https://dl.bintray.com/bahmni/rpm/rpms/bahmni-endtb-batch-1.1.0-66.noarch.rpm state=present

- name: Get bahmniapps from remote location if configured
  get_url: url={{ bahmniapps_url }}
   force=yes
   dest=/opt/bahmni-web/etc/bahmniapps.zip
   mode=0755
  when: bahmniapps_url is defined

- name: unlinking /var/www/bahmniapps
  command: unlink /var/www/bahmniapps
  when: bahmniapps_url is defined

- name: Removing endtb-bahmniapps folder
  command: rm -rf /opt/bahmni-web/etc/endtb-bahmniapps
  when: bahmniapps_url is defined

- name: Unzip downloaded bahmniapps file
  command: unzip /opt/bahmni-web/etc/bahmniapps.zip -d /opt/bahmni-web/etc/endtb-bahmniapps
  when: bahmniapps_url is defined

- name: linking /var/www/bahmniapps to entdb-release-84 bahmniapps
  command: ln -s /opt/bahmni-web/etc/endtb-bahmniapps /var/www/bahmniapps
  when: bahmniapps_url is defined
