bahmni_repo_url: http://bahmni-repo.twhosted.com/rpm/bahmni/
implementation_name: endtb
timezone: Asia/Kolkata
omods: ["https://s3.amazonaws.com/endtb-artifacts/1.6/bahmniendtb-1.6-SNAPSHOT.omod", "https://modules.openmrs.org/modulus/api/releases/1458/download/dataintegrity-omod-4.0.omod"]
