bahmni_repo_url: http://bahmni-repo.twhosted.com/rpm/bahmni/
implementation_name: endtb
timezone: Asia/Kolkata
omods: ["https://s3.amazonaws.com/endtb-artifacts/1.3/bahmniendtb-1.3-SNAPSHOT.omod", "https://s3.amazonaws.com/endtb-artifacts/1.3/bahmni-dataintegrity-omod-1.0-SNAPSHOT.omod"]
